# Generated by Django 5.0.1 on 2024-02-29 19:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glcodes', '0001_initial'),
        ('publishers', '0002_alter_publisher_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glcode',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='glcode',
            name='publisher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publishers.publisher'),
        ),
    ]
