# Generated by Django 5.0.1 on 2024-02-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_alter_publisher_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='company_id',
            field=models.IntegerField(blank=True, max_length=10, unique=True),
        ),
    ]
